info:
  app:
    version: @project.version@
spring:
  application:
    name: @project.artifactId@
  output:
    ansi:
      enabled: always
logging:
  pattern:
    level: "%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]"